export const USER_DATA_SAVE = 'USER_DATA_SAVE'
export const USER_DATA_REMOVE = 'USER_DATA_REMOVE'
export const USER_DATA_ADD_UNREAD_DIALOG = 'USER_DATA_ADD_UNREAD_DIALOG'
export const USER_DATA_REMOVE_UNREAD_DIALOG = 'USER_DATA_REMOVE_UNREAD_DIALOG'

export const JOIN_DATA_SAVE = 'JOIN_DATA_SAVE'

export const TOUR_DATA_SAVE = 'TOUR_DATA_SAVE'

export const DIALOGS_UPDATE = 'DIALOGS_UPDATE'
export const DIALOGS_CREATE_OR_UPDATE = 'DIALOGS_CREATE_OR_UPDATE'
export const DIALOGS_UPDATE_START = 'MESSAGES_UPDATE_START'
export const DIALOGS_UPDATE_FAIL = 'MESSAGES_UPDATE_FAIL'
export const DIALOGS_MARK_AS_READ = 'DIALOGS_MARK_AS_READ'

export const MESSAGES_UPDATE = 'MESSAGES_UPDATE'
export const MESSAGES_UPDATE_START = 'MESSAGES_UPDATE_START'
export const MESSAGES_UPDATE_FAIL = 'MESSAGES_UPDATE_FAIL'
